#! /bin/sh

bspc monitor -d 0 1 2 3 4 5
        
bspc config border_width                1
bspc config window_gap                  0
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true
bspc config auto_alternate              false
bspc config auto_cancel                 true
bspc config top_padding                 12
bspc config normal_border_color         "#181512"
bspc config focused_border_color        "#A9A2A2"
bspc config presel_border_color         "#AC4142"

bspc config normal_frame_opacity        0.0
bspc config focused_frame_opacity       0.05

wmname LG3D &
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &
#~/.config/bspwm/panel/init.sh &
