#! /bin/sh

# bspc monitor -d 001 010 011 100 101
bspc monitor -d 0 1 2 3 4 5
# bspc monitor -d I II III IV

bspc config border_width 0
bspc config window_gap 0
# bspc config top_padding 16
bspc config top_padding 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

compton &
xsetroot -cursor_name left_ptr &
xrdb ~/.Xresources &
~/.config/bspwm/panel/init.sh &
